Parameters:
  RockyLinuxAMI:
    Type: String
  CommonStackName:
    Type: String

Resources:
  K8sNetwork:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.1.0.0/16
      EnableDnsHostnames: False
      Tags:
        - Key: Name
          Value: k8s-master

  K8sInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: k8s-igw

  K8sInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref K8sInternetGateway
      VpcId: !Ref K8sNetwork

  K8sMasterRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref K8sNetwork
      Tags:
      - Key: Name
        Value: k8s-internet-rt

  K8sInternetRoute:
    Type: AWS::EC2::Route
    DependsOn: K8sInternetGatewayAttachment
    Properties:
       RouteTableId: !Ref K8sMasterRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId: !Ref K8sInternetGateway

  K8sMasterPublicSubnetAz1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: "10.1.1.0/24"
      #MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: k8s-public-az1
      VpcId: !Ref K8sNetwork

  K8sMasterPublicSubnetAz2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs ]
      CidrBlock: "10.1.2.0/24"
      #MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: k8s-public-az2
      VpcId: !Ref K8sNetwork

  K8sMasterPublicSubnetAz1DefaultRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref K8sMasterPublicSubnetAz1
      RouteTableId: !Ref K8sMasterRouteTable

  K8sMasterPublicSubnetAz2DefaultRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref K8sMasterPublicSubnetAz2
      RouteTableId: !Ref K8sMasterRouteTable

  K8sSSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Salt traffic
      GroupName: k8s-allow-ssh
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/8
          Description: Allow SSH from internal network
      Tags:
        - Key: Name
          Value: k8s-allow-ssh
      VpcId: !Ref K8sNetwork

  K8sMasterPublicIpAz1:
    Type: AWS::EC2::EIP
    DependsOn: K8sInternetGatewayAttachment
    Properties:
      Domain: vpc

  K8sMasterPublicIpAz2:
    Type: AWS::EC2::EIP
    DependsOn: K8sInternetGatewayAttachment
    Properties:
      Domain: vpc

  K8sNatGatewayAz1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt K8sMasterPublicIpAz1.AllocationId
      SubnetId: !Ref K8sMasterPublicSubnetAz1
      Tags:
        - Key: Name
          Value: "k8s-master-ngw-az1"

  K8sNatGatewayAz2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt K8sMasterPublicIpAz2.AllocationId
      SubnetId: !Ref K8sMasterPublicSubnetAz2
      Tags:
        - Key: Name
          Value: "k8s-master-ngw-az2"

  K8sMasterNatRouteTableAz1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref K8sNetwork
      Tags:
      - Key: Name
        Value: k8s-nat-rt-az1

  K8sMasterNatRouteTableAz2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref K8sNetwork
      Tags:
      - Key: Name
        Value: k8s-nat-rt-az2

  K8sMasterNatRouteAz1:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref K8sNatGatewayAz1
      RouteTableId: !Ref K8sMasterNatRouteTableAz1

  K8sMasterNatRouteAz2:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref K8sNatGatewayAz2
      RouteTableId: !Ref K8sMasterNatRouteTableAz2

  K8sMasterPrivateSubnetAz1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: "10.1.11.0/24"
      #MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: k8s-private-az1
      VpcId: !Ref K8sNetwork

  K8sMasterPrivateSubnetAz2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs ]
      CidrBlock: "10.1.12.0/24"
      #MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: k8s-private-az2
      VpcId: !Ref K8sNetwork

  PrivateSubnetAz1RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref K8sMasterNatRouteTableAz1
      SubnetId: !Ref K8sMasterPrivateSubnetAz1

  PrivateSubnetAz2RouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref K8sMasterNatRouteTableAz2
      SubnetId: !Ref K8sMasterPrivateSubnetAz2

  K8sMasterLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: k8s-master-lt
      LaunchTemplateData:
        ImageId: !Ref RockyLinuxAMI
        InstanceType: t2.small
        KeyName:
          Fn::ImportValue: !Sub '${CommonStackName}-SSHKeyPairName'
        SecurityGroupIds:
          - !Ref K8sSSHSecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: 'k8s-master'
        UserData:
          Fn::Base64: |
            #!/bin/bash
            dnf upgrade -y
            dnf install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
            systemctl enable amazon-ssm-agent
            systemctl start amazon-ssm-agent

  K8sMasterAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: k8s-master-ag
      DesiredCapacity: '2'
      LaunchTemplate:
        LaunchTemplateId: !Ref K8sMasterLaunchTemplate
        Version: !GetAtt K8sMasterLaunchTemplate.LatestVersionNumber
      MinSize: '0'
      MaxSize: '3'
      VPCZoneIdentifier:
        - !Ref K8sMasterPrivateSubnetAz1
        - !Ref K8sMasterPrivateSubnetAz2

Outputs:
  VPCId:
    Value: !Ref K8sNetwork
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"
  RouteTableAz1:
    Value: !Ref K8sMasterNatRouteTableAz1
    Export:
      Name: !Sub "${AWS::StackName}-RouteTableAz1"
  RouteTableAz2:
    Value: !Ref K8sMasterNatRouteTableAz2
    Export:
      Name: !Sub "${AWS::StackName}-RouteTableAz2"
