Parameters:
  RockyLinuxAMI:
    Type: String
  CommonStackName:
    Type: String

Resources:
  MgmtNetwork:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: False
      Tags:
        - Key: Name
          Value: mgmt

  MgmtInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: mgmt-igw

  MgmtInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MgmtInternetGateway
      VpcId: !Ref MgmtNetwork

  MgmtRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MgmtNetwork
      Tags:
      - Key: Name
        Value: mgmt-rt

  MgmtDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: MgmtInternetGatewayAttachment
    Properties:
       RouteTableId: !Ref MgmtRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId: !Ref MgmtInternetGateway

  MgmtDefaultSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs ] # us-east-1b
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: True
      Tags:
        - Key: Name
          Value: mgmt-default-subnet
      VpcId: !Ref MgmtNetwork

  MgmtDefaultRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MgmtDefaultSubnet
      RouteTableId: !Ref MgmtRouteTable

  MgmtSSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH traffic from anywhere
      GroupName: mgmt-allow-ssh
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: mgmt-allow-ssh
      VpcId: !Ref MgmtNetwork

  OrchestratorInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: !Ref RockyLinuxAMI
      SubnetId: !Ref MgmtDefaultSubnet
      KeyName:
        Fn::ImportValue: !Sub '${CommonStackName}-SSHKeyPairName'
      SecurityGroupIds:
        - !GetAtt MgmtSSHSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: orchestrator

Outputs:
  VPCId:
    Value: !Ref MgmtNetwork
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"
  RouteTable:
    Value: !Ref MgmtRouteTable
    Export:
      Name: !Sub "${AWS::StackName}-RouteTable"
