Parameters:
  RockyLinuxAMI:
    Type: String
  MgmtStackName:
    Type: String
  K8sMasterStackName:
    Type: String

Resources:
  MgmtK8sPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId:
        Fn::ImportValue: !Sub '${MgmtStackName}-VPCId'
      PeerVpcId:
        Fn::ImportValue: !Sub '${K8sMasterStackName}-VPCId'
      Tags:
        - Key: Name
          Value: mgmt-k8s

  MgmtK8sMasterRoute:
    Type: AWS::EC2::Route
    Properties:
       RouteTableId:
          Fn::ImportValue: !Sub '${MgmtStackName}-RouteTable'
       DestinationCidrBlock: 10.1.0.0/16
       VpcPeeringConnectionId: !Ref MgmtK8sPeeringConnection

  K8sMasterMgmtRouteAz1:
    Type: AWS::EC2::Route
    Properties:
       RouteTableId:
          Fn::ImportValue: !Sub '${K8sMasterStackName}-RouteTableAz1'
       DestinationCidrBlock: 10.0.0.0/16
       VpcPeeringConnectionId: !Ref MgmtK8sPeeringConnection

  K8sMasterMgmtRouteAz2:
    Type: AWS::EC2::Route
    Properties:
       RouteTableId:
          Fn::ImportValue: !Sub '${K8sMasterStackName}-RouteTableAz2'
       DestinationCidrBlock: 10.0.0.0/16
       VpcPeeringConnectionId: !Ref MgmtK8sPeeringConnection
